version: "3"
services:
  product-service:
    container_name: product-service
    restart: always
    build: product_service/
    ports:
    - "3000:3000"
    volumes:
    - ./product_service:/usr/src/product-service
    - /usr/src/product-service/node_modules
    depends_on:
      - tay-mall-db

  customer-service:
    container_name: customer-service
    restart: always
    build: customer_service/
    ports:
      - "3001:3000"
    volumes:
      - ./customer_service:/usr/src/customer-service
      - /usr/src/customer-service/node_modules
    depends_on:
      - tay-mall-db

  payment-service:
    container_name: payment-service
    build: payment_service/
    ports:
      - "3002:3000"
    volumes:
      - ./payment_service:/usr/src/payment-service
      - /usr/src/payment-service/node_modules
    depends_on:
      - tay-mall-db
      - rabbitmq
    links:
      - tay-mall-db
      - rabbitmq
    restart: always

  order-service:
    container_name: order-service
    restart: always
    build: order_service/
    ports:
      - "3003:3000"
    volumes:
      - ./order_service:/usr/src/order-service
      - /usr/src/order-service/node_modules
    depends_on:
      - tay-mall-db
      - rabbitmq

  tay-mall-db:
    container_name: tay-mall-db
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27018:27017"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  data:
