version: "3"
services:
  product-service:
    container_name: product-service
    restart: always
    build: product_service/
    ports:
    - "3000:3000"
    volumes:
    - ./product_service:/usr/src/product-service
    depends_on:
      - tay-mall-db

  customer-service:
    container_name: customer-service
    restart: always
    build: customer_service/
    ports:
      - "3001:3000"
    volumes:
      - ./customer_service:/usr/src/customer-service
    depends_on:
      - tay-mall-db

  payment-service:
    container_name: payment-service
    restart: always
    build: payment_service/
    ports:
      - "3002:3000"
    volumes:
      - ./payment_service:/usr/src/payment-service
    depends_on:
      - tay-mall-db
      - rabbitmq

  order-service:
    container_name: order-service
    restart: always
    build: order_service/
    ports:
      - "3003:3000"
    volumes:
      - ./order_service:/usr/src/order-service
    depends_on:
      - tay-mall-db

  tay-mall-db:
    container_name: tay-mall-db
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27018:27017"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 15672:15672

volumes:
  data:
